function Resourse() {
    return {
        index_title: "계정 만들기 또는 열기",
        index_Desc_1: "크레딧 암호화 플랫폼에서 무료 웹 지갑을 열거나 만드십시오",
        index_Desc_2: "크레딧 저장 네트워크 기반 코인으로 송금 및 결제를 해보세요",
        index_button_1: "새로운 지갑",
        index_button_2: "로그인",
        index_h2_2: "크레딧츠 블록체인",
        index_Desc_3: "가볍고 빠른 프로세싱",
        index_Desc_4: "낮은 전송 수수료",
        index_Desc_5: "브라우저 기반 어플리케이션",
        index_Desc_6: "웹 브라우저로 당신의 토큰에 접근하세요",
        index_h2_3: "크레딧츠란?",
        index_Desc_7: "크레딧츠는 블록체인의 원칙에 따라 구축된 새로운 디지털 암호화 통화 및 결제 시스템입니다",
        index_Desc_8: "크레딧츠은 자율적인 스마트 계약과 자체 내부 암호화를 갖춘 개방형 분산형 블록체인 플랫폼입니다. 이 플랫폼은 공용 데이터 레지스트리와 함께 스마트 계약을 자체 실행하여 블록체인 시스템을 위한 서비스를 사용하도록 설계되었습니다.",

        FAQ_h2: "FAQ",
        FAQ_item_1: "What is an account?",
        FAQ_item_2: "How to create a new account?",
        FAQ_item_3: "How to sign in with a previously created user account?",
        FAQ_item_4: "What is a public and private key?",
        FAQ_item_5: "What is a keyfile and what is it used for?",
        FAQ_item_6: "What operations can be performed in the user's wallet?",

        RenderKey_h1_1: "Create an Account",
        RenderKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        RenderKey_p_2: "Create a Password to generate your Keystore File and then save it",
        RenderKey_p_warning: "Create a Password to generate your Keystore File and then save it",
        RenderKey_input_placeholder: "Password",
        RenderKey_input_Error_1: "The field must not be empty",
        RenderKey_p_3: "Generate keystore file",
        RenderKey_button_1: "계속하기",

        NewKey_h1_1: "Create an Account",
        NewKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        NewKey_h2_1: "Save very carefully the Address (public) and Password (private) keys for your account",
        NewKey_label_1: "Account number, address (public key)",
        NewKey_error_1: "Invalid public key",
        NewKey_label_2: "Password to your account ( Private key to access your account)",
        NewKey_error_2: "Invalid private key",
        NewKey_inportant: "VERY IMPORTANT! Do not lose this file and do not give it to anyone. If you lose the file, then no one will be able to restore the access to your account.",
        NewKey_button_1: "계속하기",

        SignIn_h1_1: "기존 지갑 열기",
        SignIn_h1_1_InTock: "Create your own token",
        SignIn_h1_1_InSmart: "Execute smart contract",
        SignIn_p_1: "크레딧츠 플랫폼에서 거래를 수행하기 위해 지갑 열기",
        SignIn_h2_1: "지갑에 접근하기 위해 키 입력하기",
        SignIn_p_2: "프라이빗 키를 사용해 계정에 접근하기",
        SignIn_label_1: "퍼블릭 키 입력하기",
        SignIn_input_placeholder_1: "Put public key here",
        SignIn_input_error_1: "The field must not be empty",
        SignIn_label_2: "이전 단계에서 개인 키 입력하기",
        SignIn_input_placeholder_2: "Put private key here",
        SignIn_input_error_2: "The field must not be empty",
        SignIn_button_1: "계속하기",
        SignIn_h2_2: "키 파일을 입력하세요",
        SignIn_button_2: "키 파일 입력하기",
        SignIn_button_2_Error: "Invalid file key",

        

        Acc_h2_1: "지갑 / 계정",
        Acc_Desc_1: "Wallet address:",
        Acc_Desc_2: "Balance:",
        Acc_Desc_14: "Token:",
        Acc_Desc_11: "Update",
        Acc_Desc_13: "트랜잭션 수행하기",
        Acc_Desc_3: "상세 거래 내역",
        Acc_Desc_10: "스마트 컨트랙트",
        Acc_Desc_12: "토큰 생성하기",
        Acc_h2_2: "트랜잭션 수행하기",
        Acc_Desc_4: "CS나 토큰을 크레딧츠 플랫폼의 다른 계정에 전송합니다",
        Acc_h2_3: "Complete the Required Fields",
        Acc_Desc_5: "Transfer ONLY to another account on the CREDITS platform.",
        Acc_Desc_6: "CS코인 혹은 토큰 선택하기",
        Acc_Desc_7: "받는 사람 주소(크레딧츠 플랫폼 상의)",
        Acc_placeholder_1: "지갑 주소를 입력하세요",
        Acc_input_1_error: "Address field must not be empty",
        Acc_Desc_8: "크레딧츠(CS) 혹은 토큰 수량",
        Acc_placeholder_2: "0.0",
        Acc_input_2_error: "Amount field must not be empty",
        Acc_Desc_9: "크레딧츠(CS) 최대 수수료",
        Acc_placeholder_3: "0.0",
        Acc_input_3_error: "Fee field must not be empty",
        Acc_button_1: "보내기",

        Confirm_h2_1: "Check Details and Verify transaction",
        Confirm_Desc_1: "IMPORTANT!Once you approve the transaction you will NOT be able to cancel it.",
        Confirm_Desc_2: "받는이 주소(수신자)",
        Confirm_Desc_3: "전송 수량",
        Confirm_Desc_4: "전송 비용",
        Confirm_button_1: "Back",
        Confirm_button_2: "Confirm transaction",

        NewCoin_h1_1: "Add token",
        NewCoin_p_1: "On this page you can add new coin for smart contract",
        NewCoin_p_2: "Put SmartContract token",
        NewCoin_p_3: "Put coin mnemonic",
        NewCoin_button_1: "Add token",

        ConfirmTrans_h2_1: "Check Details and Verify transaction", 
        ConfirmTrans_p_1: "경고! 일단 거래를 승인하면 취소할 수 없습니다.",
        ConfirmTrans_p_2: "받는이 주소(수신자)",
        ConfirmTrans_p_3: "전송 수량",
        ConfirmTrans_p_4: "전송 비용",
        ConfirmTrans_button_1: "Back",
        ConfirmTrans_button_2: "Confirm transaction",

        ResultPayment_h1_1: "Your transaction was sent",
        ResultPayment_p_1: "CREDITS Monitor에서 상세 거래 내역을 확인하세요",
        ResultPayment_p_2: "받는이 주소(수신자)",
        ResultPayment_p_3: "전송 수량",
        ResultPayment_p_4: "전송 비용",
        ResultPayment_link_1: "계속해서 CREDITS Monitor에서 트랜잭션 보기",
        ResultPayment_button_1: "계속하기",
        
        RenderSmartContract_h1_1: "스마트 컨트랙트",
        RenderSmartContract_button_1: "Back",
        RenderSmartContract_placeholder_1: "Search contract",
        RenderSmartContract_p_1: "Choose method:",
        RenderSmartContract_button_2: "Veiw Code",
        RenderSmartContract_button_3: "Execute",

        CreateToken_h2_1: "Smart contract token",
        CreateToken_h2_2: "토큰 생성하기",
        CreateToken_p_1: "You can edit smart contract code in this field",
        CreateToken_p_2: "웹상의 혹은 금융 자산으로 사용하기 위하여 토큰을 생성하세요: 공유, 토큰화된 보안, 스테이블 코인, 로열티 프로그램, 기타 등등",
        CreateToken_button_1: "Back",
        CreateToken_button_2: "Deploy"
    };
}