function Resourse() {
    return {
        index_title: "Create or Open a New Wallet",
        index_Desc_1: "The Credits Web Wallet is a client interface for secure and easy interaction with the Credits peer-to-peer network.",
        index_Desc_2: "It allows you to transfer the Credits Coin and Tokens running on the Credits platform from one user to another and perform operations with pre-existing smart contracts in real-time.",
        index_button_1: "New Wallet",
        index_button_2: "Sign in",
        index_h2_2: "Credits blockchain",
        index_Desc_3: "Lightning-fast processing",
        index_Desc_4: "Low transaction fees",
        index_Desc_5: "Browser-based application",
        index_Desc_6: "Access your tokens via web browser",
        index_h2_3: "What is Credits?",
        index_Desc_7: "Credits is a new digital cryptocurrency and payment system, built on the principles of blockchain.",
        index_Desc_8: "Credits is an open decentralized blockchain platform with autonomous smart contracts and its own internal cryptocurrency. The platform is designed to enable services for blockchain systems using self-executing smart contracts with a public data registry.",

        FAQ_h2: "FAQ",
        FAQ_item_1: "What is an account?",
        FAQ_item_2: "How to create a new account?",
        FAQ_item_3: "How to sign in with a previously created user account?",
        FAQ_item_4: "What is a public and private key?",
        FAQ_item_5: "What is a keyfile and what is it used for?",
        FAQ_item_6: "What operations can be performed in the user's wallet?",

        RenderKey_h1_1: "Create an Account",
        RenderKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        RenderKey_p_2: "Create a Password to generate your Keystore File and then save it",
        RenderKey_p_warning: "Create a Password to generate your Keystore File and then save it",
        RenderKey_input_placeholder: "Password",
        RenderKey_input_Error_1: "The field must not be empty",
        RenderKey_p_3: "Generate keystore file",
        RenderKey_button_1: "Continue",

        NewKey_h1_1: "Create an Account",
        NewKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        NewKey_h2_1: "Save very carefully the Address (public) and Password (private) keys for your account",
        NewKey_label_1: "Account number, address (public key)",
        NewKey_error_1: "Invalid public key",
        NewKey_label_2: "Password to your account ( Private key to access your account)",
        NewKey_error_2: "Invalid private key",
        NewKey_inportant: "VERY IMPORTANT! Do not lose this file and do not give it to anyone. If you lose the file, then no one will be able to restore the access to your account.",
        NewKey_button_1: "Continue",

        SignIn_h1_1: "Log into your existing wallet",
        SignIn_h1_1_InTock: "Create your own token",
        SignIn_h1_1_InSmart: "Execute smart contract",
        SignIn_p_1: "Open your wallet to perform transactions on the Credits platform",
        SignIn_h2_1: "Enter your Keys to access your wallet",
        SignIn_p_2: "Use your Private Key to access your Account [DELETE AS Redundant]",
        SignIn_label_1: "Enter public key",
        SignIn_input_placeholder_1: "Enter public key here",
        SignIn_input_error_1: "The field must not be empty",
        SignIn_label_2: "Enter your saved private key in previous step",
        SignIn_input_placeholder_2: "Enter private key here",
        SignIn_input_error_2: "The field must not be empty",
        SignIn_button_1: "Continue",
        SignIn_h2_2: "Use existing key file",
        SignIn_button_2: "Attach Key File",
        SignIn_button_2_Error: "Invalid file key",

        

        Acc_h2_1: "Wallet",
        Acc_Desc_1: "Wallet address:",
        Acc_Desc_2: "Balance:",
        Acc_Desc_14: "Token:",
        Acc_Desc_11: "Update",
        Acc_Desc_13: "Perform a transaction",
        Acc_Desc_3: "Detailed transaction history",
        Acc_Desc_10: "Smart contracts",
        Acc_Desc_12: "Create a token",
        Acc_h2_2: "Perform a transaction",
        Acc_Desc_4: "Transfer CS or tokens ONLY to another account on the Credits platform.",
        Acc_h2_3: "Complete the Required Fields",
        Acc_Desc_5: "Transfer ONLY to another account on the CREDITS platform.",
        Acc_Desc_6: "Select CS coin or token",
        Acc_Desc_7: "Destination wallet (account number) address (on Credits platform)",
        Acc_placeholder_1: "Enter Wallet Address here",
        Acc_input_1_error: "Address field must not be empty",
        Acc_Desc_8: "Amount in Credits (CS) or tokens",
        Acc_placeholder_2: "0.0",
        Acc_input_2_error: "Amount field must not be empty",
        Acc_Desc_9: "Max Fee in Credits (CS)",
        Acc_placeholder_3: "0.0",
        Acc_input_3_error: "Fee field must not be empty",
        Acc_button_1: "Send",

        Confirm_h2_1: "Check Details and Verify transaction",
        Confirm_Desc_1: "IMPORTANT!Once you approve the transaction you will NOT be able to cancel it.",
        Confirm_Desc_2: "To Address (Recipient)",
        Confirm_Desc_3: "Transaction Amount",
        Confirm_Desc_4: "Transaction Fee",
        Confirm_button_1: "Back",
        Confirm_button_2: "Confirm transaction",

        NewCoin_h1_1: "Add token",
        NewCoin_p_1: "On this page you can add new coin for smart contract",
        NewCoin_p_2: "Put SmartContract token",
        NewCoin_p_3: "Put coin mnemonic",
        NewCoin_button_1: "Add token",

        ConfirmTrans_h2_1: "Check Details and Verify transaction", 
        ConfirmTrans_p_1: "WARNING! Once you approve the transaction you will NOT be able to cancel it.",
        ConfirmTrans_p_2: "To Address (Recipient)",
        ConfirmTrans_p_3: "Transaction Amount",
        ConfirmTrans_p_4: "Transaction Fee",
        ConfirmTrans_button_1: "Back",
        ConfirmTrans_button_2: "Confirm transaction",

        ResultPayment_h1_1: "Your transaction was sent",
        ResultPayment_p_1: "Transaction details on the CREDITS Monitor",
        ResultPayment_p_2: "To Address (Recipient)",
        ResultPayment_p_3: "Transaction Amount",
        ResultPayment_p_4: "Transaction Fee",
        ResultPayment_link_1: "View transaction on the CREDITS Monitor",
        ResultPayment_button_1: "Continue",
        
        RenderSmartContract_h1_1: "Smart contracts",
        RenderSmartContract_button_1: "Back",
        RenderSmartContract_placeholder_1: "Search contract",
        RenderSmartContract_p_1: "Choose method:",
        RenderSmartContract_button_2: "Veiw Code",
        RenderSmartContract_button_3: "Execute",

        CreateToken_h2_1: "Smart contract token",
        CreateToken_h2_2: "Create a token",
        CreateToken_p_1: "You can edit smart contract code in this field",
        CreateToken_p_2: "Create a token to use as a cyber or financial asset: share, tokenized security, stable coin, loyalty points, and others.",
        CreateToken_button_1: "Back",
        CreateToken_button_2: "Deploy"
    };
}