function Resourse() {
    return {
        index_title: "创建或打开账户",
        index_Desc_1: "在Creditscryptocurrenсy平台中创建或开设一个免费帐户。",
        index_Desc_2: "存储硬币和代币。进行转账和付款",
        index_button_1: "新账户",
        index_button_2: "登入",
        index_h2_2: "Credits区块链",
        index_Desc_3: "闪电般快速处理",
        index_Desc_4: "低廉的交易费用",
        index_Desc_5: "浏览器端应用程序",
        index_Desc_6: "在Web浏览器上发出token",
        index_h2_3: "什么是Credits？",
        index_Desc_7: "Credits是一种新的数字加密货币，也是一种基于区块链原则的支付系统。",
        index_Desc_8: "Credits是一个开放的去中心区块链平台，具有自主智能合约和内部加密货币。该平台旨在使用具有公共数据注册表的自动执行智能合约为区块链系统创建服务。",

        FAQ_h2: "FAQ",
        FAQ_item_1: "What is an account?",
        FAQ_item_2: "How to create a new account?",
        FAQ_item_3: "How to sign in with a previously created user account?",
        FAQ_item_4: "What is a public and private key?",
        FAQ_item_5: "What is a keyfile and what is it used for?",
        FAQ_item_6: "What operations can be performed in the user's wallet?",

        RenderKey_h1_1: "Create an Account",
        RenderKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        RenderKey_p_2: "Create a Password to generate your Keystore File and then save it",
        RenderKey_p_warning: "Create a Password to generate your Keystore File and then save it",
        RenderKey_input_placeholder: "Password",
        RenderKey_input_Error_1: "The field must not be empty",
        RenderKey_p_3: "Generate keystore file",
        RenderKey_button_1: "继续",

        NewKey_h1_1: "Create an Account",
        NewKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        NewKey_h2_1: "Save very carefully the Address (public) and Password (private) keys for your account",
        NewKey_label_1: "Account number, address (public key)",
        NewKey_error_1: "Invalid public key",
        NewKey_label_2: "Password to your account ( Private key to access your account)",
        NewKey_error_2: "Invalid private key",
        NewKey_inportant: "VERY IMPORTANT! Do not lose this file and do not give it to anyone. If you lose the file, then no one will be able to restore the access to your account.",
        NewKey_button_1: "继续",

        SignIn_h1_1: "解锁您的钱包",
        SignIn_h1_1_InTock: "Create your own token",
        SignIn_h1_1_InSmart: "Execute smart contract",
        SignIn_p_1: "在此页面上，您可以打开钱包并在Credits平台中进行交易",
        SignIn_h2_1: "输入您的私钥",
        SignIn_p_2: "使用您的私钥访问您的帐户。",
        SignIn_label_1: "输入公钥",
        SignIn_input_placeholder_1: "Put public key here",
        SignIn_input_error_1: "The field must not be empty",
        SignIn_label_2: "输入上一步中保存的私钥",
        SignIn_input_placeholder_2: "Put private key here",
        SignIn_input_error_2: "The field must not be empty",
        SignIn_button_1: "继续",
        SignIn_h2_2: "输入您的密钥文件",
        SignIn_button_2: "放入密钥文件",
        SignIn_button_2_Error: "Invalid file key",

        

        Acc_h2_1: "帐户",
        Acc_Desc_1: "Wallet address:",
        Acc_Desc_2: "Balance:",
        Acc_Desc_14: "Token:",
        Acc_Desc_11: "Update",
        Acc_Desc_13: "进行转账",
        Acc_Desc_3: "详细的交易记录",
        Acc_Desc_10: "智能合约",
        Acc_Desc_12: "创建一个token",
        Acc_h2_2: "进行转账",
        Acc_Desc_4: "仅将CS或令牌转移到Credits平台上的其他帐户。",
        Acc_h2_3: "Complete the Required Fields",
        Acc_Desc_5: "Transfer ONLY to another account on the CREDITS platform.",
        Acc_Desc_6: "选择CS币或token",
        Acc_Desc_7: "帐号，地址（在Credits平台上）",
        Acc_placeholder_1: "在这里输入地址",
        Acc_input_1_error: "Address field must not be empty",
        Acc_Desc_8: "Credits（CS）或代币的金额",
        Acc_placeholder_2: "0.0",
        Acc_input_2_error: "Amount field must not be empty",
        Acc_Desc_9: "Credits上的最高手续费（CS）",
        Acc_placeholder_3: "0.0",
        Acc_input_3_error: "Fee field must not be empty",
        Acc_button_1: "发送",

        Confirm_h2_1: "Check Details and Verify transaction",
        Confirm_Desc_1: "IMPORTANT!Once you approve the transaction you will NOT be able to cancel it.",
        Confirm_Desc_2: "发送到地址（收件人）",
        Confirm_Desc_3: "交易金额",
        Confirm_Desc_4: "交易费",
        Confirm_button_1: "Back",
        Confirm_button_2: "Confirm transaction",

        NewCoin_h1_1: "Add token",
        NewCoin_p_1: "On this page you can add new coin for smart contract",
        NewCoin_p_2: "Put SmartContract token",
        NewCoin_p_3: "Put coin mnemonic",
        NewCoin_button_1: "Add token",

        ConfirmTrans_h2_1: "Check Details and Verify transaction", 
        ConfirmTrans_p_1: "请注意！同意交易后，您将无法取消该交易。",
        ConfirmTrans_p_2: "发送到地址（收件人）",
        ConfirmTrans_p_3: "交易金额",
        ConfirmTrans_p_4: "交易费",
        ConfirmTrans_button_1: "Back",
        ConfirmTrans_button_2: "Confirm transaction",

        ResultPayment_h1_1: "Your transaction was sent",
        ResultPayment_p_1: "您可以在以下的CREDITS监视器上的交易详情",
        ResultPayment_p_2: "发送到地址（收件人）",
        ResultPayment_p_3: "交易金额",
        ResultPayment_p_4: "交易费",
        ResultPayment_link_1: "在CREDITS监视器上查看转账",
        ResultPayment_button_1: "继续",
        
        RenderSmartContract_h1_1: "智能合约",
        RenderSmartContract_button_1: "Back",
        RenderSmartContract_placeholder_1: "Search contract",
        RenderSmartContract_p_1: "Choose method:",
        RenderSmartContract_button_2: "Veiw Code",
        RenderSmartContract_button_3: "Execute",

        CreateToken_h2_1: "Smart contract token",
        CreateToken_h2_2: "创建一个token",
        CreateToken_p_1: "You can edit smart contract code in this field",
        CreateToken_p_2: "在这里，您可以创建token并将其用作网络或金融资产：共享，安全，稳定硬币，忠诚度积分等。",
        CreateToken_button_1: "Back",
        CreateToken_button_2: "Deploy"
    };
}