function Resourse() {
    return {
        index_title: "アカウントを作成または開く",
        index_Desc_1: "Credits暗号通貨プラットフォームで無料アカウントを作成または開く",
        index_Desc_2: "コインとトークンの保管、送金と決済",
        index_button_1: "新しいアカウント",
        index_button_2: "サインイン",
        index_h2_2: "Creditsブロックチェーン",
        index_Desc_3: "超高速処理",
        index_Desc_4: "安価な取引手数料",
        index_Desc_5: "ブラウザエンド・アプリケーション",
        index_Desc_6: "ウェブブラウザでトークンを発行",
        index_h2_3: "Creditsとは？",
        index_Desc_7: "Creditsは、新しいデジタル暗号通貨であり、ブロックチェーンの原則に基づいて構築された決済システムです。",
        index_Desc_8: "Creditsは、自律型スマートコントラクトと内部暗号通貨を備えたオープンな分散型ブロックチェーン・プラットフォームです。このプラットフォームは、パブリックデータ・レジストリで自己実行型スマートコントラクトを使用して、ブロックチェーン・システム用のサービスを作成するように設計されています。",

        FAQ_h2: "FAQ",
        FAQ_item_1: "What is an account?",
        FAQ_item_2: "How to create a new account?",
        FAQ_item_3: "How to sign in with a previously created user account?",
        FAQ_item_4: "What is a public and private key?",
        FAQ_item_5: "What is a keyfile and what is it used for?",
        FAQ_item_6: "What operations can be performed in the user's wallet?",

        RenderKey_h1_1: "Create an Account",
        RenderKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        RenderKey_p_2: "Create a Password to generate your Keystore File and then save it",
        RenderKey_p_warning: "Create a Password to generate your Keystore File and then save it",
        RenderKey_input_placeholder: "Password",
        RenderKey_input_Error_1: "The field must not be empty",
        RenderKey_p_3: "Generate keystore file",
        RenderKey_button_1: "継続",

        NewKey_h1_1: "Create an Account",
        NewKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        NewKey_h2_1: "Save very carefully the Address (public) and Password (private) keys for your account",
        NewKey_label_1: "Account number, address (public key)",
        NewKey_error_1: "Invalid public key",
        NewKey_label_2: "Password to your account ( Private key to access your account)",
        NewKey_error_2: "Invalid private key",
        NewKey_inportant: "VERY IMPORTANT! Do not lose this file and do not give it to anyone. If you lose the file, then no one will be able to restore the access to your account.",
        NewKey_button_1: "継続",

        SignIn_h1_1: "ウォレットを開錠",
        SignIn_h1_1_InTock: "Create your own token",
        SignIn_h1_1_InSmart: "Execute smart contract",
        SignIn_p_1: "このページでは、Creditsプラットフォームでウォレットを開いて取引を行うことができます。",
        SignIn_h2_1: "秘密鍵を入力",
        SignIn_p_2: "アカウントにアクセスするため秘密鍵を利用",
        SignIn_label_1: "公開鍵を入力",
        SignIn_input_placeholder_1: "Put public key here",
        SignIn_input_error_1: "The field must not be empty",
        SignIn_label_2: "前回保存した秘密鍵を入力",
        SignIn_input_placeholder_2: "Put private key here",
        SignIn_input_error_2: "The field must not be empty",
        SignIn_button_1: "継続",
        SignIn_h2_2: "Key fileを入力",
        SignIn_button_2: "key fileを入力",
        SignIn_button_2_Error: "Invalid file key",

        

        Acc_h2_1: "アカウント",
        Acc_Desc_1: "Wallet address:",
        Acc_Desc_2: "Balance:",
        Acc_Desc_14: "Token:",
        Acc_Desc_11: "Update",
        Acc_Desc_13: "トランザクションを実行",
        Acc_Desc_3: "トランザクション履歴詳細",
        Acc_Desc_10: "スマートコントラクト",
        Acc_Desc_12: "トークン作成",
        Acc_h2_2: "トランザクションを実行",
        Acc_Desc_4: "CSまたはトークンをCreditsプラットフォームの別のアカウントのみに転送します。",
        Acc_h2_3: "Complete the Required Fields",
        Acc_Desc_5: "Transfer ONLY to another account on the CREDITS platform.",
        Acc_Desc_6: "CSコインまたはトークンを選択",
        Acc_Desc_7: "アカウント番号、アドレス（Creditsプラットフォーム上）",
        Acc_placeholder_1: "ここにアドレスを入力",
        Acc_input_1_error: "Address field must not be empty",
        Acc_Desc_8: "Credits（CS）またはトークンの金額",
        Acc_placeholder_2: "0.0",
        Acc_input_2_error: "Amount field must not be empty",
        Acc_Desc_9: "Credits（CS）の最大費用",
        Acc_placeholder_3: "0.0",
        Acc_input_3_error: "Fee field must not be empty",
        Acc_button_1: "送信",

        Confirm_h2_1: "Check Details and Verify transaction",
        Confirm_Desc_1: "IMPORTANT!Once you approve the transaction you will NOT be able to cancel it.",
        Confirm_Desc_2: "アドレス（宛先）",
        Confirm_Desc_3: "トランザクション額",
        Confirm_Desc_4: "トランザクション手数料",
        Confirm_button_1: "Back",
        Confirm_button_2: "Confirm transaction",

        NewCoin_h1_1: "Add token",
        NewCoin_p_1: "On this page you can add new coin for smart contract",
        NewCoin_p_2: "Put SmartContract token",
        NewCoin_p_3: "Put coin mnemonic",
        NewCoin_button_1: "Add token",

        ConfirmTrans_h2_1: "Check Details and Verify transaction", 
        ConfirmTrans_p_1: "重要！ トランザクションを承認すると、キャンセルすることはできません。",
        ConfirmTrans_p_2: "アドレス（宛先）",
        ConfirmTrans_p_3: "トランザクション額",
        ConfirmTrans_p_4: "トランザクション手数料",
        ConfirmTrans_button_1: "Back",
        ConfirmTrans_button_2: "Confirm transaction",

        ResultPayment_h1_1: "Your transaction was sent",
        ResultPayment_p_1: "以下で、トランザクションの詳細を確認したり、Creditsモニターで取引を確認したりできます。",
        ResultPayment_p_2: "アドレス（宛先）",
        ResultPayment_p_3: "トランザクション額",
        ResultPayment_p_4: "トランザクション手数料",
        ResultPayment_link_1: "Creditsモニターでトランザクションを見る",
        ResultPayment_button_1: "継続",
        
        RenderSmartContract_h1_1: "スマートコントラクト",
        RenderSmartContract_button_1: "Back",
        RenderSmartContract_placeholder_1: "Search contract",
        RenderSmartContract_p_1: "Choose method:",
        RenderSmartContract_button_2: "Veiw Code",
        RenderSmartContract_button_3: "Execute",

        CreateToken_h2_1: "Smart contract token",
        CreateToken_h2_2: "トークン作成",
        CreateToken_p_1: "You can edit smart contract code in this field",
        CreateToken_p_2: "ここでトークンを作成し、サイバーまたは金融資産として使用できます。シェア、セキュリティ、ステーブルコイン、ロイヤリティポイントなど。",
        CreateToken_button_1: "Back",
        CreateToken_button_2: "Deploy"
    };
}