function Resourse() {
    return {
        index_title: "Tạo hoặc mở một ví mới",
        index_Desc_1: "Tạo hoặc mở ví web miễn phí trên nền tảng tiền điện tử Credits.",
        index_Desc_2: "Lưu trữ tiền xu Credits và mã thông báo dựa trên mạng. Thực hiện chuyển khoản và thanh toán",
        index_button_1: "Ví mới",
        index_button_2: "Đăng nhập",
        index_h2_2: "Credits blockchain",
        index_Desc_3: "Xử lý nhanh như chớp",
        index_Desc_4: "Phí giao dịch thấp",
        index_Desc_5: "Ứng dụng dựa trên trình duyệt",
        index_Desc_6: "Truy cập mã thông báo của bạn thông qua trình duyệt web",
        index_h2_3: "Credits là gì?",
        index_Desc_7: "Credits là một hệ thống thanh toán và tiền điện tử kỹ thuật số mới, được xây dựng trên các nguyên tắc của blockchain.",
        index_Desc_8: "Credits là một nền tảng blockchain phi tập trung mở với các hợp đồng thông minh tự trị và tiền điện tử nội bộ của riêng nó. Nền tảng được thiết kế để cho phép các dịch vụ cho các hệ thống blockchain sử dụng các hợp đồng thông minh tự thực hiện với đăng ký dữ liệu công khai.",

        FAQ_h2: "FAQ",
        FAQ_item_1: "What is an account?",
        FAQ_item_2: "How to create a new account?",
        FAQ_item_3: "How to sign in with a previously created user account?",
        FAQ_item_4: "What is a public and private key?",
        FAQ_item_5: "What is a keyfile and what is it used for?",
        FAQ_item_6: "What operations can be performed in the user's wallet?",

        RenderKey_h1_1: "Create an Account",
        RenderKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        RenderKey_p_2: "Create a Password to generate your Keystore File and then save it",
        RenderKey_p_warning: "Create a Password to generate your Keystore File and then save it",
        RenderKey_input_placeholder: "Password",
        RenderKey_input_Error_1: "The field must not be empty",
        RenderKey_p_3: "Generate keystore file",
        RenderKey_button_1: "Tiếp tục",

        NewKey_h1_1: "Create an Account",
        NewKey_p_1: "To make payments with Credits (CS) cryptocurrency, tokens or use smart contracts, you need to create an account in the Credits blockchain. It’s very easy",
        NewKey_h2_1: "Save very carefully the Address (public) and Password (private) keys for your account",
        NewKey_label_1: "Account number, address (public key)",
        NewKey_error_1: "Invalid public key",
        NewKey_label_2: "Password to your account ( Private key to access your account)",
        NewKey_error_2: "Invalid private key",
        NewKey_inportant: "VERY IMPORTANT! Do not lose this file and do not give it to anyone. If you lose the file, then no one will be able to restore the access to your account.",
        NewKey_button_1: "Tiếp tục",

        SignIn_h1_1: "Mở ví hiện tại của bạn",
        SignIn_h1_1_InTock: "Create your own token",
        SignIn_h1_1_InSmart: "Execute smart contract",
        SignIn_p_1: "Mở ví của bạn để thực hiện giao dịch trên nền tảng Credits",
        SignIn_h2_1: "Nhập khóa của bạn để truy cập vào ví của bạn",
        SignIn_p_2: "Sử dụng Khóa riêng để truy cập vào tài khoản của bạn [DELETE AS Redundant]",
        SignIn_label_1: "Nhập khóa công khai",
        SignIn_input_placeholder_1: "Put public key here",
        SignIn_input_error_1: "The field must not be empty",
        SignIn_label_2: "Nhập khóa riêng đã lưu của bạn vào bước trước",
        SignIn_input_placeholder_2: "Put private key here",
        SignIn_input_error_2: "The field must not be empty",
        SignIn_button_1: "Tiếp tục",
        SignIn_h2_2: "Sử dụng và tập tin khóa hiện có",
        SignIn_button_2: "Đính kèm tập tin chính",
        SignIn_button_2_Error: "Invalid file key",

        

        Acc_h2_1: "Ví / Tài khoản",
        Acc_Desc_1: "Wallet address:",
        Acc_Desc_2: "Balance:",
        Acc_Desc_14: "Token:",
        Acc_Desc_11: "Update",
        Acc_Desc_13: "Thực hiện giao dịch",
        Acc_Desc_3: "Lịch sử giao dịch chi tiết",
        Acc_Desc_10: "Hợp đồng thông minh",
        Acc_Desc_12: "Tạo mã thông báo",
        Acc_h2_2: "Thực hiện giao dịch",
        Acc_Desc_4: " CS hoặc mã thông báo CHỈ được chuyển sang tài khoản khác trên nền tảng Credits",
        Acc_h2_3: "Complete the Required Fields",
        Acc_Desc_5: "Transfer ONLY to another account on the CREDITS platform.",
        Acc_Desc_6: "Chọn coin CS hoặc mã thông báo",
        Acc_Desc_7: "Địa chỉ ví (số tài khoản) đích (trên nền tảng Credits)",
        Acc_placeholder_1: "Nhập địa chỉ ví tại đây",
        Acc_input_1_error: "Address field must not be empty",
        Acc_Desc_8: "Số tiền trong Credits (CS) hoặc mã thông báo",
        Acc_placeholder_2: "0.0",
        Acc_input_2_error: "Amount field must not be empty",
        Acc_Desc_9: "Phí tối đa trong Credits (CS)",
        Acc_placeholder_3: "0.0",
        Acc_input_3_error: "Fee field must not be empty",
        Acc_button_1: "Gửi",

        Confirm_h2_1: "Check Details and Verify transaction",
        Confirm_Desc_1: "IMPORTANT!Once you approve the transaction you will NOT be able to cancel it.",
        Confirm_Desc_2: "Đến địa chỉ (Người nhận)",
        Confirm_Desc_3: "số tiền giao dịch",
        Confirm_Desc_4: "Phí vận chuyển",
        Confirm_button_1: "Back",
        Confirm_button_2: "Confirm transaction",

        NewCoin_h1_1: "Add token",
        NewCoin_p_1: "On this page you can add new coin for smart contract",
        NewCoin_p_2: "Put SmartContract token",
        NewCoin_p_3: "Put coin mnemonic",
        NewCoin_button_1: "Add token",

        ConfirmTrans_h2_1: "Check Details and Verify transaction", 
        ConfirmTrans_p_1: "CẢNH BÁO! Khi bạn phê duyệt giao dịch, bạn sẽ KHÔNG thể hủy bỏ nó.",
        ConfirmTrans_p_2: "Đến địa chỉ (Người nhận)",
        ConfirmTrans_p_3: "số tiền giao dịch",
        ConfirmTrans_p_4: "Phí vận chuyển",
        ConfirmTrans_button_1: "Back",
        ConfirmTrans_button_2: "Confirm transaction",

        ResultPayment_h1_1: "Your transaction was sent",
        ResultPayment_p_1: "Chi tiết giao dịch trên CREDITS Monitor",
        ResultPayment_p_2: "Đến địa chỉ (Người nhận)",
        ResultPayment_p_3: "số tiền giao dịch",
        ResultPayment_p_4: "Phí vận chuyển",
        ResultPayment_link_1: "Xem giao dịch trên CREDITS Monitor",
        ResultPayment_button_1: "Tiếp tục",
        
        RenderSmartContract_h1_1: "Hợp đồng thông minh",
        RenderSmartContract_button_1: "Back",
        RenderSmartContract_placeholder_1: "Search contract",
        RenderSmartContract_p_1: "Choose method:",
        RenderSmartContract_button_2: "Veiw Code",
        RenderSmartContract_button_3: "Execute",

        CreateToken_h2_1: "Smart contract token",
        CreateToken_h2_2: "Tạo mã thông báo",
        CreateToken_p_1: "You can edit smart contract code in this field",
        CreateToken_p_2: "Tạo mã thông báo để sử dụng làm tài sản mạng hoặc tài chính: chia sẻ, bảo mật mã thông báo, đồng tiền ổn định, điểm trung thành và những người khác.",
        CreateToken_button_1: "Back",
        CreateToken_button_2: "Deploy"
    };
}