/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ClassObject : TBase
{
  private List<ByteCodeObject> _byteCodeObjects;
  private byte[] _instance;

  public List<ByteCodeObject> ByteCodeObjects
  {
    get
    {
      return _byteCodeObjects;
    }
    set
    {
      __isset.byteCodeObjects = true;
      this._byteCodeObjects = value;
    }
  }

  public byte[] Instance
  {
    get
    {
      return _instance;
    }
    set
    {
      __isset.instance = true;
      this._instance = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool byteCodeObjects;
    public bool instance;
  }

  public ClassObject() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ByteCodeObjects = new List<ByteCodeObject>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  ByteCodeObject _elem2;
                  _elem2 = new ByteCodeObject();
                  _elem2.Read(iprot);
                  ByteCodeObjects.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Instance = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ClassObject");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ByteCodeObjects != null && __isset.byteCodeObjects) {
        field.Name = "byteCodeObjects";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ByteCodeObjects.Count));
          foreach (ByteCodeObject _iter3 in ByteCodeObjects)
          {
            _iter3.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Instance != null && __isset.instance) {
        field.Name = "instance";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Instance);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ClassObject(");
    bool __first = true;
    if (ByteCodeObjects != null && __isset.byteCodeObjects) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ByteCodeObjects: ");
      __sb.Append(ByteCodeObjects);
    }
    if (Instance != null && __isset.instance) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Instance: ");
      __sb.Append(Instance);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

