/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi_4_3
{
#if !SILVERLIGHT
    [Serializable]
#endif
    public partial class Annotation : TBase
    {
        private string _name;
        private Dictionary<string, string> _arguments;

        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                __isset.name = true;
                this._name = value;
            }
        }

        public Dictionary<string, string> Arguments
        {
            get
            {
                return _arguments;
            }
            set
            {
                __isset.arguments = true;
                this._arguments = value;
            }
        }


        public Isset __isset;
#if !SILVERLIGHT
        [Serializable]
#endif
        public struct Isset
        {
            public bool name;
            public bool arguments;
        }

        public Annotation()
        {
        }

        public void Read(TProtocol iprot)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                iprot.ReadStructBegin();
                while (true)
                {
                    field = iprot.ReadFieldBegin();
                    if (field.Type == TType.Stop)
                    {
                        break;
                    }
                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.String)
                            {
                                Name = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 2:
                            if (field.Type == TType.Map)
                            {
                                {
                                    Arguments = new Dictionary<string, string>();
                                    TMap _map21 = iprot.ReadMapBegin();
                                    for (int _i22 = 0; _i22 < _map21.Count; ++_i22)
                                    {
                                        string _key23;
                                        string _val24;
                                        _key23 = iprot.ReadString();
                                        _val24 = iprot.ReadString();
                                        Arguments[_key23] = _val24;
                                    }
                                    iprot.ReadMapEnd();
                                }
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        default:
                            TProtocolUtil.Skip(iprot, field.Type);
                            break;
                    }
                    iprot.ReadFieldEnd();
                }
                iprot.ReadStructEnd();
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public void Write(TProtocol oprot)
        {
            oprot.IncrementRecursionDepth();
            try
            {
                TStruct struc = new TStruct("Annotation");
                oprot.WriteStructBegin(struc);
                TField field = new TField();
                if (Name != null && __isset.name)
                {
                    field.Name = "name";
                    field.Type = TType.String;
                    field.ID = 1;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Name);
                    oprot.WriteFieldEnd();
                }
                if (Arguments != null && __isset.arguments)
                {
                    field.Name = "arguments";
                    field.Type = TType.Map;
                    field.ID = 2;
                    oprot.WriteFieldBegin(field);
                    {
                        oprot.WriteMapBegin(new TMap(TType.String, TType.String, Arguments.Count));
                        foreach (string _iter25 in Arguments.Keys)
                        {
                            oprot.WriteString(_iter25);
                            oprot.WriteString(Arguments[_iter25]);
                        }
                        oprot.WriteMapEnd();
                    }
                    oprot.WriteFieldEnd();
                }
                oprot.WriteFieldStop();
                oprot.WriteStructEnd();
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString()
        {
            StringBuilder __sb = new StringBuilder("Annotation(");
            bool __first = true;
            if (Name != null && __isset.name)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Name: ");
                __sb.Append(Name);
            }
            if (Arguments != null && __isset.arguments)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Arguments: ");
                __sb.Append(Arguments);
            }
            __sb.Append(")");
            return __sb.ToString();
        }

    }

}