/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi_4_3
{
#if !SILVERLIGHT
    [Serializable]
#endif
    public partial class MethodArgument : TBase
    {
        private string _type;
        private string _name;
        private List<Annotation> _annotations;

        public string Type
        {
            get
            {
                return _type;
            }
            set
            {
                __isset.type = true;
                this._type = value;
            }
        }

        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                __isset.name = true;
                this._name = value;
            }
        }

        public List<Annotation> Annotations
        {
            get
            {
                return _annotations;
            }
            set
            {
                __isset.annotations = true;
                this._annotations = value;
            }
        }


        public Isset __isset;
#if !SILVERLIGHT
        [Serializable]
#endif
        public struct Isset
        {
            public bool type;
            public bool name;
            public bool annotations;
        }

        public MethodArgument()
        {
        }

        public void Read(TProtocol iprot)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                iprot.ReadStructBegin();
                while (true)
                {
                    field = iprot.ReadFieldBegin();
                    if (field.Type == TType.Stop)
                    {
                        break;
                    }
                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.String)
                            {
                                Type = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 2:
                            if (field.Type == TType.String)
                            {
                                Name = iprot.ReadString();
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 3:
                            if (field.Type == TType.List)
                            {
                                {
                                    Annotations = new List<Annotation>();
                                    TList _list26 = iprot.ReadListBegin();
                                    for (int _i27 = 0; _i27 < _list26.Count; ++_i27)
                                    {
                                        Annotation _elem28;
                                        _elem28 = new Annotation();
                                        _elem28.Read(iprot);
                                        Annotations.Add(_elem28);
                                    }
                                    iprot.ReadListEnd();
                                }
                            }
                            else
                            {
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        default:
                            TProtocolUtil.Skip(iprot, field.Type);
                            break;
                    }
                    iprot.ReadFieldEnd();
                }
                iprot.ReadStructEnd();
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public void Write(TProtocol oprot)
        {
            oprot.IncrementRecursionDepth();
            try
            {
                TStruct struc = new TStruct("MethodArgument");
                oprot.WriteStructBegin(struc);
                TField field = new TField();
                if (Type != null && __isset.type)
                {
                    field.Name = "type";
                    field.Type = TType.String;
                    field.ID = 1;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Type);
                    oprot.WriteFieldEnd();
                }
                if (Name != null && __isset.name)
                {
                    field.Name = "name";
                    field.Type = TType.String;
                    field.ID = 2;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Name);
                    oprot.WriteFieldEnd();
                }
                if (Annotations != null && __isset.annotations)
                {
                    field.Name = "annotations";
                    field.Type = TType.List;
                    field.ID = 3;
                    oprot.WriteFieldBegin(field);
                    {
                        oprot.WriteListBegin(new TList(TType.Struct, Annotations.Count));
                        foreach (Annotation _iter29 in Annotations)
                        {
                            _iter29.Write(oprot);
                        }
                        oprot.WriteListEnd();
                    }
                    oprot.WriteFieldEnd();
                }
                oprot.WriteFieldStop();
                oprot.WriteStructEnd();
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString()
        {
            StringBuilder __sb = new StringBuilder("MethodArgument(");
            bool __first = true;
            if (Type != null && __isset.type)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Type: ");
                __sb.Append(Type);
            }
            if (Name != null && __isset.name)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Name: ");
                __sb.Append(Name);
            }
            if (Annotations != null && __isset.annotations)
            {
                if (!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Annotations: ");
                __sb.Append(Annotations);
            }
            __sb.Append(")");
            return __sb.ToString();
        }

    }

}