/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Amount : TBase
  {

    public int Integral { get; set; }

    public long Fraction { get; set; }

    public Amount() {
      this.Integral = 0;
      this.Fraction = 0;
    }

    public Amount(int integral, long fraction) : this() {
      this.Integral = integral;
      this.Fraction = fraction;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_integral = false;
        bool isset_fraction = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Integral = iprot.ReadI32();
                isset_integral = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I64) {
                Fraction = iprot.ReadI64();
                isset_fraction = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_integral)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Integral not set");
        if (!isset_fraction)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Fraction not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Amount");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "integral";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Integral);
        oprot.WriteFieldEnd();
        field.Name = "fraction";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Fraction);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Amount(");
      __sb.Append(", Integral: ");
      __sb.Append(Integral);
      __sb.Append(", Fraction: ");
      __sb.Append(Fraction);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
