/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NodeApi
{
  public enum SmartOperationState
  {
    SOS_Pending = 0,
    SOS_Success = 1,
    SOS_Failed = 2,
  }
}
