/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NodeApi
{
  public enum TokensListSortField
  {
    TL_Code = 0,
    TL_Name = 1,
    TL_Address = 2,
    TL_TotalSupply = 3,
    TL_HoldersCount = 4,
    TL_TransfersCount = 5,
    TL_TransactionsCount = 6,
  }
}
