/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NodeApi
{
  public enum TokenStandart
  {
    NotAToken = 0,
    CreditsBasic = 1,
    CreditsExtended = 2,
  }
}
