/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NodeApi
{
  public enum TokenHoldersSortField
  {
    TH_Balance = 0,
    TH_TransfersCount = 1,
  }
}
