/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TokenTransferTransInfo : TBase
  {
    private string _code;
    private byte[] _sender;
    private byte[] _receiver;
    private string _amount;
    private SmartOperationState _state;
    private TransactionId _stateTransaction;
    private bool _transferSuccess;

    public string Code
    {
      get
      {
        return _code;
      }
      set
      {
        __isset.code = true;
        this._code = value;
      }
    }

    public byte[] Sender
    {
      get
      {
        return _sender;
      }
      set
      {
        __isset.sender = true;
        this._sender = value;
      }
    }

    public byte[] Receiver
    {
      get
      {
        return _receiver;
      }
      set
      {
        __isset.receiver = true;
        this._receiver = value;
      }
    }

    public string Amount
    {
      get
      {
        return _amount;
      }
      set
      {
        __isset.amount = true;
        this._amount = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="SmartOperationState"/>
    /// </summary>
    public SmartOperationState State
    {
      get
      {
        return _state;
      }
      set
      {
        __isset.state = true;
        this._state = value;
      }
    }

    public TransactionId StateTransaction
    {
      get
      {
        return _stateTransaction;
      }
      set
      {
        __isset.stateTransaction = true;
        this._stateTransaction = value;
      }
    }

    public bool TransferSuccess
    {
      get
      {
        return _transferSuccess;
      }
      set
      {
        __isset.transferSuccess = true;
        this._transferSuccess = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool code;
      public bool sender;
      public bool receiver;
      public bool amount;
      public bool state;
      public bool stateTransaction;
      public bool transferSuccess;
    }

    public TokenTransferTransInfo() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Code = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Sender = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Receiver = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Amount = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I32) {
                State = (SmartOperationState)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Struct) {
                StateTransaction = new TransactionId();
                StateTransaction.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.Bool) {
                TransferSuccess = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TokenTransferTransInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Code != null && __isset.code) {
          field.Name = "code";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Code);
          oprot.WriteFieldEnd();
        }
        if (Sender != null && __isset.sender) {
          field.Name = "sender";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(Sender);
          oprot.WriteFieldEnd();
        }
        if (Receiver != null && __isset.receiver) {
          field.Name = "receiver";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(Receiver);
          oprot.WriteFieldEnd();
        }
        if (Amount != null && __isset.amount) {
          field.Name = "amount";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Amount);
          oprot.WriteFieldEnd();
        }
        if (__isset.state) {
          field.Name = "state";
          field.Type = TType.I32;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)State);
          oprot.WriteFieldEnd();
        }
        if (StateTransaction != null && __isset.stateTransaction) {
          field.Name = "stateTransaction";
          field.Type = TType.Struct;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          StateTransaction.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.transferSuccess) {
          field.Name = "transferSuccess";
          field.Type = TType.Bool;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(TransferSuccess);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TokenTransferTransInfo(");
      bool __first = true;
      if (Code != null && __isset.code) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Code: ");
        __sb.Append(Code);
      }
      if (Sender != null && __isset.sender) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Sender: ");
        __sb.Append(Sender);
      }
      if (Receiver != null && __isset.receiver) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Receiver: ");
        __sb.Append(Receiver);
      }
      if (Amount != null && __isset.amount) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Amount: ");
        __sb.Append(Amount);
      }
      if (__isset.state) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("State: ");
        __sb.Append(State);
      }
      if (StateTransaction != null && __isset.stateTransaction) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StateTransaction: ");
        __sb.Append(StateTransaction== null ? "<null>" : StateTransaction.ToString());
      }
      if (__isset.transferSuccess) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TransferSuccess: ");
        __sb.Append(TransferSuccess);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
