/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NodeApi
{
  public enum TransactionType
  {
    TT_Normal = 0,
    TT_SmartDeploy = 1,
    TT_SmartExecute = 2,
    TT_SmartState = 3,
  }
}
