/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NodeApi
{
  public enum TransactionState
  {
    INVALID = 0,
    VALID = 1,
    INPROGRESS = 2,
  }
}
