/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TransactionsStateGetResult : TBase
  {
    private APIResponse _status;
    private Dictionary<long, TransactionState> _states;
    private int _roundNum;

    public APIResponse Status
    {
      get
      {
        return _status;
      }
      set
      {
        __isset.status = true;
        this._status = value;
      }
    }

    public Dictionary<long, TransactionState> States
    {
      get
      {
        return _states;
      }
      set
      {
        __isset.states = true;
        this._states = value;
      }
    }

    public int RoundNum
    {
      get
      {
        return _roundNum;
      }
      set
      {
        __isset.roundNum = true;
        this._roundNum = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool status;
      public bool states;
      public bool roundNum;
    }

    public TransactionsStateGetResult() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Status = new APIResponse();
                Status.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Map) {
                {
                  States = new Dictionary<long, TransactionState>();
                  TMap _map45 = iprot.ReadMapBegin();
                  for( int _i46 = 0; _i46 < _map45.Count; ++_i46)
                  {
                    long _key47;
                    TransactionState _val48;
                    _key47 = iprot.ReadI64();
                    _val48 = (TransactionState)iprot.ReadI32();
                    States[_key47] = _val48;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                RoundNum = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TransactionsStateGetResult");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Status != null && __isset.status) {
          field.Name = "status";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Status.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (States != null && __isset.states) {
          field.Name = "states";
          field.Type = TType.Map;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.I64, TType.I32, States.Count));
            foreach (long _iter49 in States.Keys)
            {
              oprot.WriteI64(_iter49);
              oprot.WriteI32((int)States[_iter49]);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.roundNum) {
          field.Name = "roundNum";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(RoundNum);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TransactionsStateGetResult(");
      bool __first = true;
      if (Status != null && __isset.status) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Status: ");
        __sb.Append(Status== null ? "<null>" : Status.ToString());
      }
      if (States != null && __isset.states) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("States: ");
        __sb.Append(States);
      }
      if (__isset.roundNum) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RoundNum: ");
        __sb.Append(RoundNum);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
