/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NodeApi_4_3
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ExtraFee : TBase
  {
    private Amount _sum;
    private string _comment;
    private TransactionId _transactionId;

    public Amount Sum
    {
      get
      {
        return _sum;
      }
      set
      {
        __isset.sum = true;
        this._sum = value;
      }
    }

    public string Comment
    {
      get
      {
        return _comment;
      }
      set
      {
        __isset.comment = true;
        this._comment = value;
      }
    }

    public TransactionId TransactionId
    {
      get
      {
        return _transactionId;
      }
      set
      {
        __isset.transactionId = true;
        this._transactionId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool sum;
      public bool comment;
      public bool transactionId;
    }

    public ExtraFee() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Sum = new Amount();
                Sum.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Comment = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                TransactionId = new TransactionId();
                TransactionId.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ExtraFee");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Sum != null && __isset.sum) {
          field.Name = "sum";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Sum.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Comment != null && __isset.comment) {
          field.Name = "comment";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Comment);
          oprot.WriteFieldEnd();
        }
        if (TransactionId != null && __isset.transactionId) {
          field.Name = "transactionId";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          TransactionId.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ExtraFee(");
      bool __first = true;
      if (Sum != null && __isset.sum) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Sum: ");
        __sb.Append(Sum== null ? "<null>" : Sum.ToString());
      }
      if (Comment != null && __isset.comment) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Comment: ");
        __sb.Append(Comment);
      }
      if (TransactionId != null && __isset.transactionId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TransactionId: ");
        __sb.Append(TransactionId== null ? "<null>" : TransactionId.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
